version: 2.1

jobs:
  deploy-frontend-test:
    docker:
      - image: cimg/node:20.0.0
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: Run npm
          command: |
            npm install && npm test
  deploy-frontend-dev:
    docker:
      - image: cimg/node:20.0.0
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:XM+2xRjrCCSH/Frn3FMhEbTaB4RS9hNa9Wm54+iINww"
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: docker24
          docker_layer_caching: true
      - run:
          name: Run npm
          command: |
            npm install

      - run: CI=false sudo apt update
      - run: CI=false sudo apt-get install rsync

      - run:
          name: build file
          command: |
            CI=false npm run build

      - run:
          name: ssh login
          command: |
            rsync -va -e 'ssh -p 7822 -o StrictHostKeyChecking=no'  --delete   dist/ .htaccess  skillz@103.72.76.68:nnpc/frontend

workflows:
  version: 2
  nnpc_frontend_deploy:
    jobs:
      - deploy-frontend-test
      - deploy-frontend-dev # Use the pre-configured job, deploy-via-git
        # requires:
        #   - deploy-frontend-test
        # filters:
        #   branches:
        #     only: dev
