version: 2.1

jobs:
  deploy-frontend-test:
    docker:
      - image: cimg/node:20.0.0
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run:
          name: Run npm
          command: |
            npm install && npm test
  deploy-frontend-dev:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:XM+2xRjrCCSH/Frn3FMhEbTaB4RS9hNa9Wm54+iINww"
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run:
          name: Run npm
          command: |
            cd Frontend && npm install

      - run: CI=false sudo apt update
      - run: CI=false sudo apt-get install rsync

      - run:
          name: Update known hosts
          command: ssh-keyscan -H 185.160.67.60 >> ~/.ssh/known_hosts && cat ~/.ssh/known_hosts
      - run:
          name: build file
          command: |
            cd Frontend && CI=false npm run build

      - run:
          name: ssh login
          command: |
            rsync -va -e 'ssh -p 7822 -o StrictHostKeyChecking=no'  --delete   Frontend/dist/ Frontend/.htaccess  skillz@185.160.67.60:revenuehub/frontend
      # - run:
      #     name: ssh and run migration on live server
      #     command: |
      #       ssh bartumen@192.254.235.94 && cd devapi.bartumenergy.com &&  php artisan migrate && ls && exit

workflows:
  version: 2
  revenue_hub_deploy:
    jobs:
      - deploy-frontend-test
      - deploy-frontend-dev: # Use the pre-configured job, deploy-via-git
          filters:
            branches:
              only: dev

      # - deploy-nest: # Use the pre-configured job, deploy-via-git
      #     filters:
      #       branches:
      #         only: nest
