export enum FileType {
    JPEG = 'image/jpeg',
    PNG = 'image/png',
    PDF = 'application/pdf',
    EXCEL = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    WEBP = 'image/webp',
    WORD = 'application/msword',
    TXT = 'text/plain',
    DOC = 'application/msword',
    DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    CSV = 'text/csv',
    MP3 = 'audio/mpeg',
    MP4 = 'video/mp4',
    SVG = 'image/svg+xml',
    HTML = 'text/html',
    JSON = 'application/json',
    XML = 'application/xml',
    ZIP = 'application/zip',
    TAR = 'application/x-tar',
    RAR = 'application/vnd.rar',
    GIF = 'image/gif',
}