import greenIcon from '../public/assets/greenIcon.png'


export const fundersData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement LTD',
        companyEmail: 'default@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Direct Customer',
        selectedDates: [
            '10/July/2023',
            '14/Nov/2023',
            '23/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank Nigeria',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/May/2023',
            '23/June/2023',
            '25/Aug/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        selectedDates: [
            '8/Jan/2023',
            '17/Mar/2023',
            '29/Sept/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano International Limited',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway Corporation',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/May/2023',
            '23/June/2023',
            '25/Aug/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank for Africa',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust Bank',
        companyType: 'Direct Customer',
        selectedDates: [
            '8/Jan/2023',
            '17/Mar/2023',
            '29/Sept/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City Records',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023',
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic Press',
        companyType: 'Direct Customer',
        selectedDates: [
            '10/July/2023',
            '14/Nov/2023',
            '23/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian Railway Corporation',
        companyType: 'Direct Customer',
        selectedDates: [
            '8/Jan/2023',
            '17/Mar/2023',
            '29/Sept/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction Limited',
        companyType: 'Direct Customer',
        selectedDates: [
            '11/Feb/2023',
            '19/April/2023',
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/May/2023',
            '23/June/2023',
            '25/Aug/2023',
        ],
        status: 'Date Approved',
        action: '',
    },

]


export const AgreementData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement ',
        companyEmail: 'default@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        agreementType: 'GSPA Agreement',
        datesent: '25/Feb/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '19/Oct/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank ',
        companyType: 'Direct Customer',
        agreementType: 'Addendum Agreement',
        datesent: '05/Jun/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '11/May/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano  Corporation',
        companyType: 'Strategic partner',
        agreementType: 'Addendum Agreement',
        datesent: '08/Dec/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway ',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '14/Sept/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '18/May/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        agreementType: 'Supplement Agreement',
        datesent: '04/April/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '17/Oct/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank ',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '11/Nov/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '07/Mar/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Strategic partner',
        agreementType: 'GSPA Agreement',
        datesent: '20/May/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '15/Sept/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust ',
        companyType: 'Direct Customer',
        agreementType: 'Addendum Agreement',
        datesent: '14/Feb/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City ',
        companyType: 'Strategic partner',
        agreementType: 'GSPA Agreement',
        datesent: '19/July/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '01/Dec/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic ',
        companyType: 'Strategic partner',
        agreementType: 'Addendum Agreement',
        datesent: '24/May/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian  Corporation',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '10/Jan/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction ',
        companyType: 'Direct Customer',
        agreementType: 'Supplement Agreement',
        datesent: '11/Feb/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Strategic partner',
        agreementType: 'Addendum Agreement',
        datesent: '18/May/2023',
        status: 'Unsigned',
        action: '',
    },

]


export const TenderTypeData = [
    {
        id: 1,
        sn: greenIcon,
        companyname: 'Dangote Cement ',
        companyEmail: 'default@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        tenderType: 'Open Tenders',
        dateopened: '25/Feb/2023',
        category: 'Procurement Tenders',
        action: '',
    },
    {
        sn: greenIcon,
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Strategic partner',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        tenderType: 'Open Tenders',
        dateopened: '19/Oct/2023',
        category: 'Procurement Tenders',
        action: '',
    },
    {
        sn: greenIcon,
        id: 3,
        companyname: 'Fidelity Bank ',
        companyType: 'Direct Customer',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State. (Coordinates 6.778N and 3.55609E. ',
        tenderType: 'Open Tenders',
        dateopened: '05/Jun/2023',
        category: 'Procurement Tenders',
        action: '',
    },
    {
        sn: greenIcon,
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        tenderType: 'Open Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '11/May/2023',
        category: 'Procurement Tenders',
        action: '',
    },
    {
        sn: greenIcon,
        id: 5,
        companyname: 'Mikano  Corporation',
        companyType: 'Strategic partner',
        tenderType: 'Open Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '08/Dec/2023',
        category: 'Procurement Tenders',
        action: '',
    },
    {
        id: 6,
        sn: greenIcon,
        companyname: 'Nigerian Railway ',
        companyType: 'Direct Customer',
        tenderType: 'Open Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '14/Sept/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 7,
        sn: greenIcon,
        companyname: 'Oando',
        companyType: 'Strategic partner',
        tenderType: 'Open Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '18/May/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 8,
        sn: greenIcon,
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        tenderType: 'Open Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '04/April/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 9,
        sn: greenIcon,
        companyname: 'Dotts Media House',
        companyType: 'Strategic partner',
        tenderType: 'Closed Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '17/Oct/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 10,
        sn: greenIcon,
        companyname: 'United Bank ',
        companyType: 'Strategic partner',
        tenderType: 'Closed Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '11/Nov/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 11,
        sn: greenIcon,
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        tenderType: 'Closed Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '07/Mar/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 12,
        sn: greenIcon,
        companyname: 'Kabo Air',
        companyType: 'Strategic partner',
        tenderType: 'Closed Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '20/May/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 13,
        sn: greenIcon,
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        tenderType: 'Closed Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '15/Sept/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 14,
        sn: greenIcon,
        companyname: 'Guaranty Trust ',
        companyType: 'Direct Customer',
        tenderType: 'Closed Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '14/Feb/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 15,
        sn: greenIcon,
        companyname: 'Chocolate City ',
        companyType: 'Strategic partner',
        tenderType: 'Closed Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '19/July/2023',
        category: 'Construction Tenders',
        action: '',
    },
    {
        id: 16,
        sn: greenIcon,
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        tenderType: 'Closed Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '01/Dec/2023',
        category: 'Procurement Tenders',
        action: '',
    },
    {
        id: 17,
        sn: greenIcon,
        companyname: 'Cassava Republic ',
        companyType: 'Strategic partner',
        tenderType: 'Closed Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '24/May/2023',
        category: 'Procurement Tenders',
        action: '',
    },
    {
        id: 18,
        sn: greenIcon,
        companyname: 'Nigerian  Corporation',
        companyType: 'Strategic partner',
        tenderType: 'Open Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '10/Jan/2023',
        category: 'Procurement Tenders',
        action: '',
    },
    {
        id: 19,
        sn: greenIcon,
        companyname: 'ROCAD Construction ',
        companyType: 'Direct Customer',
        tenderType: 'Open Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '11/Feb/2023',
        category: 'Procurement Tenders',
        action: '',
    },
    {
        id: 20,
        sn: greenIcon,
        companyname: 'Wema Bank',
        companyType: 'Strategic partner',
        tenderType: 'Open Tenders',
        titleDescription: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        description: 'Metal manufacturing Nigeria Limited is a registered company in Nigeria with a Factory located at KM 20 Ikorodu-Shagamu Road, Gbara Village, Ogijo, Ogun State (Coordinates 6.778N and 3.55609E. ',
        dateopened: '18/May/2023',
        category: 'Procurement Tenders',
        action: '',
    },

]


export const ComplaintData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement ',
        companyEmail: 'default@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '25/Feb/2023',
        status: 'Resolving',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '19/Oct/2023',
        status: 'Resolved',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank ',
        companyType: 'Direct Customer',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '05/Jun/2023',
        status: 'Resolving',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '11/May/2023',
        status: 'Resolving',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano  Corporation',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '08/Dec/2023',
        status: 'Resolved',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway ',
        companyType: 'Direct Customer',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '14/Sept/2023',
        status: 'Resolved',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '18/May/2023',
        status: 'Resolved',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '04/April/2023',
        status: 'New',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '17/Oct/2023',
        status: 'New',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank ',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '11/Nov/2023',
        status: 'New',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '07/Mar/2023',
        status: 'New',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '20/May/2023',
        status: 'Resolving',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '15/Sept/2023',
        status: 'Resolving',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust ',
        companyType: 'Direct Customer',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '14/Feb/2023',
        status: ' Resolving',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City ',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '19/July/2023',
        status: 'Resolving',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '01/Dec/2023',
        status: 'Resolved',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic ',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '24/May/2023',
        status: 'Resolved',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian  Corporation',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '10/Jan/2023',
        status: 'Resolved',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction ',
        companyType: 'Direct Customer',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '11/Feb/2023',
        status: 'New',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Strategic partner',
        issue: 'Gas Delivery timeline overdue be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ',
        datereceived: '18/May/2023',
        status: 'New',
        action: '',
    },

]



export const FeedbackData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement ',
        companyEmail: 'default@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '25/Feb/2023',
        status: 'Sent',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '19/Oct/2023',
        status: 'Sent',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank ',
        companyType: 'Direct Customer',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '05/Jun/2023',
        status: 'Sent',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '11/May/2023',
        status: 'Sent',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano  Corporation',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '08/Dec/2023',
        status: 'Feedback Pending',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway ',
        companyType: 'Direct Customer',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '14/Sept/2023',
        status: 'Feedback Pending',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '18/May/2023',
        status: 'Feedback Pending',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '04/April/2023',
        status: 'Feedback Pending',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '17/Oct/2023',
        status: 'Sent',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank ',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '11/Nov/2023',
        status: 'Sent',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '07/Mar/2023',
        status: 'Sent',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '20/May/2023',
        status: 'Sent',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '15/Sept/2023',
        status: 'Feedback Pending',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust ',
        companyType: 'Direct Customer',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '14/Feb/2023',
        status: 'Feedback Pending',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City ',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '19/July/2023',
        status: 'Feedback Pending',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '01/Dec/2023',
        status: 'Feedback Pending',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic ',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '24/May/2023',
        status: 'Feedback Pending',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian  Corporation',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '10/Jan/2023',
        status: 'Sent',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction ',
        companyType: 'Direct Customer',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '11/Feb/2023',
        status: 'Sent',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Strategic partner',
        subject: 'Gas Delivery Timeline Overdue ',
        datereceived: '18/May/2023',
        status: 'Sent',
        action: '',
    },

]


export const DailyFrequencyData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement ',
        companyEmail: 'default@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        frequency: 'Daily',
        datesent: '25/Feb/2022',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '19/Oct/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank ',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        datesent: '05/Jun/2022',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        datesent: '11/May/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano  Corporation',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '08/Dec/2024',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway ',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        datesent: '14/Sept/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '18/May/2025',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        datesent: '04/April/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '17/Oct/2024',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank ',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '11/Nov/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        datesent: '07/Mar/2025',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '20/May/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        datesent: '15/Sept/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust ',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        datesent: '14/Feb/2022',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City ',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '19/July/2024',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        datesent: '01/Dec/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic ',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '24/May/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian  Corporation',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '10/Jan/2022',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction ',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        datesent: '11/Feb/2023',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        datesent: '18/May/2024',
        value: '662,008,000.00',
        rate: '1200/Scf',
        amount: '794,409,600.00',
        action: '',
    },

]


export const TenderTitleData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement ',
        companyEmail: 'default@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '25/Feb/2022',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'COBD',
            }
        ],
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Strategic partner',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '19/Oct/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'COBD',
            }
        ],
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank ',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '05/Jun/2022',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '11/May/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'HR',
            }
        ],
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano  Corporation',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '08/Dec/2024',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'HR',
            }
        ],
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway ',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '14/Sept/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '18/May/2025',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '04/April/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '17/Oct/2024',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank ',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '11/Nov/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '07/Mar/2025',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '20/May/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '15/Sept/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust ',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '14/Feb/2022',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City ',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '19/July/2024',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '01/Dec/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic ',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '24/May/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian  Corporation',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '10/Jan/2022',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction ',
        companyType: 'Direct Customer',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '11/Feb/2023',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Strategic partner',
        frequency: 'Daily',
        tenderTitle: 'Gas Supply to Metal Manufacturing Nigeria Limited.',
        datesubmitted: '18/May/2024',
        details: [
            {
                type: 'Open Tender',
                type2: 'Procurement Tender',
                dept: 'ADMIN',
            }
        ],
        action: '',
    },

]


export const EoiRequestData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement ',
        companyEmail: 'company@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        customerID: '542023',
        status: 'New',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyEmail: 'company@email.com',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        customerID: '542023',
        status: 'Approved',
        approverName: 'Osoigwe Wilfred',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank ',
        companyEmail: 'company@email.com',
        companyType: 'Direct Customer',
        agreementType: 'Addendum Agreement',
        customerID: '542023',
        status: 'New',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        companyEmail: 'company@email.com',
        agreementType: 'GSPA Agreement',
        customerID: '542023',
        status: 'New',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano  Corporation',
        companyEmail: 'company@email.com',
        companyType: 'Strategic partner',
        agreementType: 'Addendum Agreement',
        customerID: '542023',
        status: 'New',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway ',
        companyEmail: 'company@email.com',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        customerID: '542023',
        approverName: 'Osoigwe Wilfred',
        status: 'Approved',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Strategic partner',
        companyEmail: 'company@email.com',
        agreementType: 'Supplement Agreement',
        customerID: '542023',
        status: 'Approved',
        approverName: 'Osoigwe Wilfred',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyEmail: 'company@email.com',
        companyType: 'Direct Customer',
        agreementType: 'Supplement Agreement',
        customerID: '542023',
        status: 'Disapproved',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyEmail: 'company@email.com',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        customerID: '542023',
        status: 'Pending',
        approverName: 'Osoigwe Wilfred',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank ',
        companyEmail: 'company@email.com',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        customerID: '542023',
        status: 'Approved',
        approverName: 'Osoigwe Wilfred',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyEmail: 'company@email.com',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        customerID: '542023',
        status: 'Approved',
        approverName: 'Osoigwe Wilfred',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Strategic partner',
        companyEmail: 'company@email.com',
        agreementType: 'GSPA Agreement',
        customerID: '542023',
        status: 'Approved',
        approverName: 'Osoigwe Wilfred',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        companyEmail: 'company@email.com',
        agreementType: 'GSPA Agreement',
        customerID: '542023',
        status: 'Disapproved',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust ',
        companyType: 'Direct Customer',
        companyEmail: 'company@email.com',
        agreementType: 'Addendum Agreement',
        customerID: '542023',
        status: 'New',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City ',
        companyType: 'Strategic partner',
        companyEmail: 'company@email.com',
        agreementType: 'GSPA Agreement',
        customerID: '542023',
        status: 'Pending',
        approverName: 'Osoigwe Wilfred',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyEmail: 'company@email.com',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        customerID: '542023',
        status: 'New',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic ',
        companyType: 'Strategic partner',
        companyEmail: 'company@email.com',
        agreementType: 'Addendum Agreement',
        customerID: '542023',
        status: 'New',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian  Corporation',
        companyEmail: 'company@email.com',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        customerID: '542023',
        approverName: 'Osoigwe Wilfred',
        status: 'Approved',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction ',
        companyEmail: 'company@email.com',
        companyType: 'Direct Customer',
        agreementType: 'Supplement Agreement',
        customerID: '542023',
        status: 'Approved',
        approverName: 'Osoigwe Wilfred',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Strategic partner',
        companyEmail: 'company@email.com',
        agreementType: 'Addendum Agreement',
        customerID: '542023',
        status: 'Approved',
        approverName: 'Osoigwe Wilfred',
        action: '',
    },

]


export const ProcessingCustomerData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement ',
        companyType: 'Direct Customer',
        request: 'In Progress',
        ddqform: 'Not Started',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Strategic partner',
        request: 'In Progress',
        ddqform: 'Not Started',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank ',
        companyType: 'Direct Customer',
        request: 'In Progress',
        ddqform: 'Not Started',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        request: 'In Progress',
        ddqform: 'Not Started',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano  Corporation',
        companyType: 'Strategic partner',
        request: 'Approved',
        ddqform: 'In Progress',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'Select site visit dates',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway ',
        companyType: 'Direct Customer',
        request: 'Approved',
        ddqform: 'Not Started',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'Site request approval awaiting',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Strategic partner',
        request: 'Approved',
        ddqform: 'Completed',
        sitevisits: 'Completed',
        analysis: 'In Progress',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'DDQ Awaiting ',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        request: 'Approved',
        ddqform: 'Completed',
        sitevisits: 'Not Started',
        analysis: 'Completed',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'DDQ Awaiting ',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyType: 'Strategic partner',
        request: 'Disapproved',
        ddqform: 'Not Started',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'Choose project funder',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank ',
        companyType: 'Strategic partner',
        request: 'Disapproved',
        ddqform: 'Not Started',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'Choose project funder',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        request: 'In Progress',
        ddqform: 'Not Started',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'Choose project funder',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Strategic partner',
        request: 'Approved',
        ddqform: 'In Progress',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        request: 'Approved',
        ddqform: 'In Progress',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust ',
        companyType: 'Direct Customer',
        request: 'Disapproved',
        ddqform: 'Not Started',
        sitevisits: 'Not Started',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City ',
        companyType: 'Strategic partner',
        request: 'In Progress',
        ddqform: 'Not Started',
        sitevisits: 'In Progress',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        request: 'In Progress',
        ddqform: 'Not Started',
        sitevisits: 'In Progress',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic ',
        companyType: 'Strategic partner',
        request: 'In Progress',
        ddqform: 'Not Started',
        sitevisits: 'In Progress',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian  Corporation',
        companyType: 'Strategic partner',
        request: 'Approved',
        ddqform: 'Not Started',
        sitevisits: 'In Progress',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction ',
        companyType: 'Direct Customer',
        request: 'Approved',
        ddqform: 'Not Started',
        sitevisits: 'In Progress',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Strategic partner',
        request: 'Approved',
        ddqform: 'Not Started',
        sitevisits: 'In Progress',
        analysis: 'Not Started',
        agreement: 'Not Started',
        connectProject: 'Not Started',
        statusUpdate: 'EOI awaiting approval',
        action: '',
    },

]