export const fundersData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement LTD',
        companyEmail: 'default@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Direct Customer',
        selectedDates: [
            '10/July/2023',
            '14/Nov/2023', 
            '23/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank Nigeria',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/May/2023',
            '23/June/2023', 
            '25/Aug/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        selectedDates: [
            '8/Jan/2023',
            '17/Mar/2023', 
            '29/Sept/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano International Limited',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway Corporation',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/May/2023',
            '23/June/2023', 
            '25/Aug/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank for Africa',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust Bank',
        companyType: 'Direct Customer',
        selectedDates: [
            '8/Jan/2023',
            '17/Mar/2023', 
            '29/Sept/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City Records',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic Press',
        companyType: 'Direct Customer',
        selectedDates: [
            '10/July/2023',
            '14/Nov/2023', 
            '23/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian Railway Corporation',
        companyType: 'Direct Customer',
        selectedDates: [
            '8/Jan/2023',
            '17/Mar/2023', 
            '29/Sept/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction Limited',
        companyType: 'Direct Customer',
        selectedDates: [
            '11/Feb/2023',
            '19/April/2023', 
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/May/2023',
            '23/June/2023', 
            '25/Aug/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
   
]




export const AgreementData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement ',
        companyEmail: 'default@email.com',
        companyType: 'Direct Customer',
        companyNumber: '000-000-0000',
        companyAddress: 'Default Address',
        agreementType: 'GSPA Agreement',
        datesent: '25/Feb/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'BUA Cement',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '19/Oct/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Fidelity Bank ',
        companyType: 'Direct Customer',
        agreementType: 'Addendum Agreement',
        datesent: '05/Jun/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Julius Berger',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '11/May/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Mikano  Corporation',
        companyType: 'Strategic partner',
        agreementType: 'Addendum Agreement',
        datesent: '08/Dec/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Nigerian Railway ',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '14/Sept/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Oando',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '18/May/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Shell Nigeria',
        companyType: 'Direct Customer',
        agreementType: 'Supplement Agreement',
        datesent: '04/April/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dotts Media House',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '17/Oct/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'United Bank ',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '11/Nov/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Leadway Company',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '07/Mar/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Kabo Air',
        companyType: 'Strategic partner',
        agreementType: 'GSPA Agreement',
        datesent: '20/May/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'John Holt plc',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '15/Sept/2023',
        status: 'Signed',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Guaranty Trust ',
        companyType: 'Direct Customer',
        agreementType: 'Addendum Agreement',
        datesent: '14/Feb/2023',
        status: ' Unsigned',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Chocolate City ',
        companyType: 'Strategic partner',
        agreementType: 'GSPA Agreement',
        datesent: '19/July/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Chanchangi Airlines',
        companyType: 'Direct Customer',
        agreementType: 'GSPA Agreement',
        datesent: '01/Dec/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Cassava Republic ',
        companyType: 'Strategic partner',
        agreementType: 'Addendum Agreement',
        datesent: '24/May/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Nigerian  Corporation',
        companyType: 'Strategic partner',
        agreementType: 'Supplement Agreement',
        datesent: '10/Jan/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'ROCAD Construction ',
        companyType: 'Direct Customer',
        agreementType: 'Supplement Agreement',
        datesent: '11/Feb/2023',
        status: 'Unsigned',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Wema Bank',
        companyType: 'Strategic partner',
        agreementType: 'Addendum Agreement',
        datesent: '18/May/2023',
        status: 'Unsigned',
        action: '',
    },
   
]