export const fundersData = [
    {
        id: 1,
        sn: '01',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        sn: '02',
        id: 2,
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        sn: '03',
        id: 3,
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        sn: '04',
        id: 4,
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        sn: '05',
        id: 5,
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 6,
        sn: '06',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 7,
        sn: '07',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 8,
        sn: '08',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 9,
        sn: '09',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 10,
        sn: '10',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 11,
        sn: '11',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 12,
        sn: '12',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 13,
        sn: '13',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 14,
        sn: '14',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 15,
        sn: '15',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Dates Selected',
        action: '',
    },
    {
        id: 16,
        sn: '16',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 17,
        sn: '17',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 18,
        sn: '18',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Request Approval',
        action: '',
    },
    {
        id: 19,
        sn: '19',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
    {
        id: 20,
        sn: '20',
        companyname: 'Dangote Cement LTD',
        companyType: 'Direct Customer',
        selectedDates: [
            '18/June/2023',
            '19/June/2023', 
            '20/June/2023',
        ],
        status: 'Date Approved',
        action: '',
    },
   
]